{% set name = "paramz" %}
{% set version = "0.9.6" %}
{% set sha256 = "0917211c0f083f344e7f1bc997e0d713dbc147b6380bc19f606119394f820b9a" %}


package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sods/paramz/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy >=1.7
    - scipy
    - six
    - decorator >=4.0.10
test:
  imports:
    - paramz

about:
  home: https://github.com/sods/paramz
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Parameterization Framework for parameterized model creation and handling.'
  doc_url: https://pythonhosted.org/paramz
  dev_url: https://github.com/sods/paramz

extra:
  recipe-maintainers:
    - dirmeier
    - jan-janssen
