schema_version: 1

context:
  name: paramz
  version: "0.10.0"
  sha256: e8db01b771949169d71e425228dca1610f71ed86a7f675254f32414299c2c088
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/sods/paramz/archive/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  file_name: ${{ name }}-${{ version }}.tar.gz

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python 3.11.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy >=2
    - scipy
    - six
    - decorator >=4.0.10

tests:
  - python:
      imports:
        - paramz
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Parameterization Framework for parameterized model creation and handling.
  homepage: https://github.com/sods/paramz
  repository: https://github.com/sods/paramz
  documentation: https://pythonhosted.org/paramz

extra:
  recipe-maintainers:
    - dirmeier
    - jan-janssen
